// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanHang.Infrastructure.Context;

#nullable disable

namespace QuanLyBanHang.Infrastructure.Migrations
{
    [DbContext(typeof(QlkinhdoanhContext))]
    [Migration("20240421011737_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Avatar1")
                        .HasColumnType("image")
                        .HasColumnName("AVATAR");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<int?>("Nhanvienid")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENID");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__AVATAR__3214EC27B1419861");

                    b.HasIndex("Nhanvienid");

                    b.ToTable("AVATAR", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Chitietdonhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DONGIA");

                    b.Property<int?>("Donhangid")
                        .HasColumnType("int")
                        .HasColumnName("DONHANGID");

                    b.Property<int?>("Sanphamid")
                        .HasColumnType("int")
                        .HasColumnName("SANPHAMID");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__CHITIETD__3214EC275F4960B2");

                    b.HasIndex("Donhangid");

                    b.HasIndex("Sanphamid");

                    b.ToTable("CHITIETDONHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Chitietphieumuahang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DONGIA");

                    b.Property<int?>("Phieumuahangid")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUMUAHANGID");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tensanpham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSANPHAM");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__CHITIETP__3214EC272D89F422");

                    b.HasIndex("Phieumuahangid");

                    b.ToTable("CHITIETPHIEUMUAHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Congnocuakhachhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<int?>("Donhangid")
                        .HasColumnType("int")
                        .HasColumnName("DONHANGID");

                    b.Property<DateTime?>("Hanthanhtoan")
                        .HasColumnType("datetime")
                        .HasColumnName("HANTHANHTOAN");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<decimal?>("Sotienconno")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SOTIENCONNO");

                    b.Property<decimal?>("Sotiendathanhtoan")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SOTIENDATHANHTOAN");

                    b.Property<decimal?>("Tongtienphaithanhtoa")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("TONGTIENPHAITHANHTOA");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__CONGNOCU__3214EC27D50F88C9");

                    b.HasIndex("Donhangid");

                    b.ToTable("CONGNOCUAKHACHHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Congnovoinhacungcap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<DateTime?>("Hanthanhtoan")
                        .HasColumnType("datetime")
                        .HasColumnName("HANTHANHTOAN");

                    b.Property<int?>("Phieumuahangid")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUMUAHANGID");

                    b.Property<decimal?>("Sotienconno")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SOTIENCONNO");

                    b.Property<decimal?>("Sotiendathanhtoan")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SOTIENDATHANHTOAN");

                    b.Property<string>("Tennhacungcap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNHACUNGCAP");

                    b.Property<decimal?>("Tongtienphaithanhtoa")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("TONGTIENPHAITHANHTOA");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__CONGNOVO__3214EC274029AA8F");

                    b.HasIndex("Phieumuahangid");

                    b.ToTable("CONGNOVOINHACUNGCAP", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Donhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Conno")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("CONNO");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<decimal?>("Dathanhtoan")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DATHANHTOAN");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Diachigiaohang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHIGIAOHANG");

                    b.Property<int?>("Khachhangid")
                        .HasColumnType("int")
                        .HasColumnName("KHACHHANGID");

                    b.Property<DateTime?>("Ngaytaodon")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAODON");

                    b.Property<int?>("Nhanvienid")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENID");

                    b.Property<decimal?>("Thanhtien")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("THANHTIEN");

                    b.Property<int?>("Tinhtrangid")
                        .HasColumnType("int")
                        .HasColumnName("TINHTRANGID");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__DONHANG__3214EC27728139FB");

                    b.HasIndex("Khachhangid");

                    b.HasIndex("Nhanvienid");

                    b.HasIndex("Tinhtrangid");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Imagesanpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<byte[]>("Img")
                        .HasColumnType("image")
                        .HasColumnName("IMG");

                    b.Property<int?>("Sanphamid")
                        .HasColumnType("int")
                        .HasColumnName("SANPHAMID");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__IMAGESAN__3214EC27DC243997");

                    b.HasIndex("Sanphamid");

                    b.ToTable("IMAGESANPHAM", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Khachhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__KHACHHAN__3214EC27E69DEF11");

                    b.HasIndex(new[] { "Sodienthoai" }, "UQ__KHACHHAN__7670E299BCD7CBBB")
                        .IsUnique()
                        .HasFilter("[SODIENTHOAI] IS NOT NULL");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Tenkho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKHO");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__KHO__3214EC27D54C52E7");

                    b.ToTable("KHO", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Loaisanpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Tenloaisanpham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAISANPHAM");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__LOAISANP__3214EC27ED074F8D");

                    b.ToTable("LOAISANPHAM", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Nhacungcap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<string>("Tennhacungcap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNHACUNGCAP");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__NHACUNGC__3214EC27C47808F8");

                    b.HasIndex(new[] { "Sodienthoai" }, "UQ__NHACUNGC__7670E2998E50F7D8")
                        .IsUnique()
                        .HasFilter("[SODIENTHOAI] IS NOT NULL");

                    b.ToTable("NHACUNGCAP", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Nhanvien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHUCVU");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Matkhau")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<string>("Tennhanvien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNHANVIEN");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__NHANVIEN__3214EC27D2F73E3E");

                    b.HasIndex(new[] { "Sodienthoai" }, "UQ__NHANVIEN__7670E299CBCB98CF")
                        .IsUnique()
                        .HasFilter("[SODIENTHOAI] IS NOT NULL");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Phieumuahang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<DateTime?>("Ngaymuahang")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYMUAHANG");

                    b.Property<int?>("Nhacungcapid")
                        .HasColumnType("int")
                        .HasColumnName("NHACUNGCAPID");

                    b.Property<int?>("Nhanvienid")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENID");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__PHIEUMUA__3214EC27F4637B26");

                    b.HasIndex("Nhacungcapid");

                    b.HasIndex("Nhanvienid");

                    b.ToTable("PHIEUMUAHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Sanpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baohanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BAOHANH");

                    b.Property<string>("Chatlieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHATLIEU");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<decimal?>("Giaban")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("GIABAN");

                    b.Property<int?>("Khoid")
                        .HasColumnType("int")
                        .HasColumnName("KHOID");

                    b.Property<int?>("Loaisanphamid")
                        .HasColumnType("int")
                        .HasColumnName("LOAISANPHAMID");

                    b.Property<string>("Macsac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MACSAC");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<int?>("Soluongton")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGTON");

                    b.Property<string>("Tensanpham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSANPHAM");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__SANPHAM__3214EC2791A3EB55");

                    b.HasIndex("Khoid");

                    b.HasIndex("Loaisanphamid");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Tinhtrang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATEDAT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("int")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("Deletedat")
                        .HasColumnType("datetime")
                        .HasColumnName("DELETEDAT");

                    b.Property<int?>("Deletedby")
                        .HasColumnType("int")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Tentinhtrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTINHTRANG");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATEDAT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("int")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id")
                        .HasName("PK__TINHTRAN__3214EC272C8730EA");

                    b.ToTable("TINHTRANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Avatar", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Avatars")
                        .HasForeignKey("Nhanvienid")
                        .HasConstraintName("FK__AVATAR__NHANVIEN__3C69FB99");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Chitietdonhang", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Donhang", "Donhang")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Donhangid")
                        .HasConstraintName("FK__CHITIETDO__DONHA__5441852A");

                    b.HasOne("QuanLyBanHang.Domain.Entities.Sanpham", "Sanpham")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Sanphamid")
                        .HasConstraintName("FK__CHITIETDO__SANPH__5535A963");

                    b.Navigation("Donhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Chitietphieumuahang", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Phieumuahang", "Phieumuahang")
                        .WithMany("Chitietphieumuahangs")
                        .HasForeignKey("Phieumuahangid")
                        .HasConstraintName("FK__CHITIETPH__PHIEU__619B8048");

                    b.Navigation("Phieumuahang");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Congnocuakhachhang", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Donhang", "Donhang")
                        .WithMany("Congnocuakhachhangs")
                        .HasForeignKey("Donhangid")
                        .HasConstraintName("FK__CONGNOCUA__DONHA__5165187F");

                    b.Navigation("Donhang");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Congnovoinhacungcap", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Phieumuahang", "Phieumuahang")
                        .WithMany("Congnovoinhacungcaps")
                        .HasForeignKey("Phieumuahangid")
                        .HasConstraintName("FK__CONGNOVOI__PHIEU__5EBF139D");

                    b.Navigation("Phieumuahang");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Donhang", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Khachhang", "Khachhang")
                        .WithMany("Donhangs")
                        .HasForeignKey("Khachhangid")
                        .HasConstraintName("FK__DONHANG__KHACHHA__4CA06362");

                    b.HasOne("QuanLyBanHang.Domain.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Donhangs")
                        .HasForeignKey("Nhanvienid")
                        .HasConstraintName("FK__DONHANG__NHANVIE__4D94879B");

                    b.HasOne("QuanLyBanHang.Domain.Entities.Tinhtrang", "Tinhtrang")
                        .WithMany("Donhangs")
                        .HasForeignKey("Tinhtrangid")
                        .HasConstraintName("FK__DONHANG__TINHTRA__4E88ABD4");

                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");

                    b.Navigation("Tinhtrang");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Imagesanpham", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Sanpham", "Sanpham")
                        .WithMany("Imagesanphams")
                        .HasForeignKey("Sanphamid")
                        .HasConstraintName("FK__IMAGESANP__SANPH__44FF419A");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Phieumuahang", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Nhacungcap", "Nhacungcap")
                        .WithMany("Phieumuahangs")
                        .HasForeignKey("Nhacungcapid")
                        .HasConstraintName("FK__PHIEUMUAH__NHACU__5AEE82B9");

                    b.HasOne("QuanLyBanHang.Domain.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Phieumuahangs")
                        .HasForeignKey("Nhanvienid")
                        .HasConstraintName("FK__PHIEUMUAH__NHANV__5BE2A6F2");

                    b.Navigation("Nhacungcap");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Sanpham", b =>
                {
                    b.HasOne("QuanLyBanHang.Domain.Entities.Kho", "Kho")
                        .WithMany("Sanphams")
                        .HasForeignKey("Khoid")
                        .HasConstraintName("FK__SANPHAM__KHOID__4222D4EF");

                    b.HasOne("QuanLyBanHang.Domain.Entities.Loaisanpham", "Loaisanpham")
                        .WithMany("Sanphams")
                        .HasForeignKey("Loaisanphamid")
                        .HasConstraintName("FK__SANPHAM__LOAISAN__412EB0B6");

                    b.Navigation("Kho");

                    b.Navigation("Loaisanpham");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Donhang", b =>
                {
                    b.Navigation("Chitietdonhangs");

                    b.Navigation("Congnocuakhachhangs");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Khachhang", b =>
                {
                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Kho", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Loaisanpham", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Nhacungcap", b =>
                {
                    b.Navigation("Phieumuahangs");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Nhanvien", b =>
                {
                    b.Navigation("Avatars");

                    b.Navigation("Donhangs");

                    b.Navigation("Phieumuahangs");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Phieumuahang", b =>
                {
                    b.Navigation("Chitietphieumuahangs");

                    b.Navigation("Congnovoinhacungcaps");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Sanpham", b =>
                {
                    b.Navigation("Chitietdonhangs");

                    b.Navigation("Imagesanphams");
                });

            modelBuilder.Entity("QuanLyBanHang.Domain.Entities.Tinhtrang", b =>
                {
                    b.Navigation("Donhangs");
                });
#pragma warning restore 612, 618
        }
    }
}
